baseURL: "https://reinbugnot.github.io" 
title: Rein Bugnot
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv/
          weight: 1 
        - name: Projects
          url: projects/
          weight: 2
        - name: Blog
          url: blog/
          weight: 3

params:
    description: "I am a Data Scientist with 4+ years of experience in Machine Learning and A.I. I took a Master's Degree in Artificial Intelligence in Nanyang Technological University, Singapore. I'm passionate in building Data Science solutions to solve business problems."
    author: Rein Bugnot
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rein Bugnot
          subtitle: 
            "I solve problems using Data Science and AI. ü§ñ <br> <br> 

            4 years of experience in Data Science and AI, including machine learning, data analysis, time series analysis, computer vision (PyTorch & Keras), generative AI, natural language processing (NLP), large language models (LLMs), stable diffusion (A111 & ComfyUI), and AI Ethics & Trustworthiness. <br> <br>
            
            üéì Master of Science in Artificial Intelligence, NTU Singapore <br> 
            ‚öôÔ∏è Former CEO of SmarterMeter Inc. (Building something new! üöÄ) <br> 
            üèÜ Magsaysay Future Engineer and Technologist Awardee 2019 <br> 
            üîß Licensed Electronics Engineer (PH) <br> <br>
            
            <hr>"
          imageUrl: "Casual Pic - Square.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Rein Bugnot
          buttons:
            - name: CV
              url: BUGNOT - RESUME v2.pdf
            - name: Projects
              url: projects/
            - name: Blog
              url: blog/

    socialIcons:
        - name: Email
          url: mailto:reinbugnot@gmail.com
        - name: Linkedin
          url: https://www.linkedin.com/in/reinbugnot/
        - name: GitHub
          url: https://github.com/reinbugnot

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rein Bugnot"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2